# Copyright (C) 2026 GitHub @YorokobiMaster
# SPDX-License-Identifier: Apache-2.0

# Source-built modules only. Paths are relative to DASH_KLEAF_OUT.
# Includes the deployed selection and explicit dash.config additions.
# Exported-symbol coverage was checked against these modules and vmlinux;
# broad MTK modinfo provider names are not a device-specific allowlist.

BOARD_VENDOR_RAMDISK_KERNEL_MODULES := \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/8250_mtk.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/adapter_class.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/adsp.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/aee_aed.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/aee_hangdet.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/aee_rs.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66.user/drivers/perf/arm_dsu_pmu.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/arm_smmu_v3.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66.user/drivers/mtd/devices/block2mtd.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/blocktag.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/bootprof.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/bq28z610.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/bus-parity.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/cache-parity.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/cam_fs.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/ccci_auxadc.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/ccci_md_all.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/ccci_util_lib.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/ccmni.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/charger_class.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66.user/drivers/mtd/chips/chipreg.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/clk-chk-mt6991.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/clk-common.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/clk-dbg-mt6991.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/clk-fmeter-mt6991.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/clk-mt6991-adsp.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/clk-mt6991-bus.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/clk-mt6991-cam.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/clk-mt6991-img.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/clk-mt6991-mdpsys.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/clk-mt6991-mmsys.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/clk-mt6991-peri.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/clk-mt6991-vcodec.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/clk-mt6991.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/clkbuf.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/cmdq-platform-mt6991.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/cmdq_helper_inf.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/cqhci.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/crash_module.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/dbg_error_flag.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/dbgtop-drm.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/debug_ext.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/device-apc-common.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/device-apc-mt6991.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66.user/drivers/gpu/drm/display/drm_display_helper.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66.user/drivers/gpu/drm/drm_dma_helper.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/emi-mpu.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/emi-slb.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/emi.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/extcon-mtk-usb.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/extdev_io_class.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/ffa_v11.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/gic-ram-parity.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/hl7603.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/hwid.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/i2c-mt65xx.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66.user/drivers/iio/buffer/industrialio-triggered-buffer.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/iommu_debug.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/irq-dbg.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/ise-trusty-ipc.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/ise-trusty-log.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/ise-trusty-virtio.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/ise-trusty.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/ise_lpm.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66.user/drivers/iio/buffer/kfifo_buf.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/last_bus.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/leds-color21024.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/leds-mtk-disp.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/leds-mtk-pwm.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/leds-mtk.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66.user/lib/crypto/libarc4.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/load_track.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/log_store.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mca_charge_mievent.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mca_event.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mca_log.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mca_sysfs.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mddp.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mdp_drv_mt6991.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mediatek-cpufreq-hw.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mediatek-drm.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mi_memory.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mi_stack.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mi_t1_gpio.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mi_ubt.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mi_ubt_test.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/miev.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mitee.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mkp.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mm-fake-engine.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mmprofile.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mmqos-common.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mmqos-mt6991.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/monitor_hang.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mrdump.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mt6316-regulator.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mt6363-regulator.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mt6373-regulator.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mt6375-auxadc.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mt6379-adc.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mt6379-battery.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mt6379-chg.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mt6379-regulator.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mt6379s.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mt6681-auxadc.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mt6681-core.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mt6681-regulator.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mt6685-audclk.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mt6685-core.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mt6991_dcm.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66.user/drivers/mtd/mtd.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66.user/drivers/mtd/mtd_blkdevs.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66.user/drivers/mtd/mtdblock.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66.user/drivers/mtd/mtdoops.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-afe-external.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-cmdq-drv-ext.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-dvfsrc-devfreq.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-dvfsrc-helper.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-dvfsrc-regulator.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-dvfsrc.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-emi.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-hw-semaphore.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-i3c-i2c-wrap.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-i3c-master-mt69xx.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-icc-core.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-ise-mailbox.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-mbox-mailbox.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-mbox.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-mmc-dbg.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-mmc.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-mmdebug-vcp.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-mmdvfs-debug.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-mmdvfs-ftrace.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-mmdvfs-v3-start.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-mmdvfs-v3.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-mmdvfs.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-mminfra-debug.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-mminfra-imax.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-mml-mt6991.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-mml.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-pmic-keys.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-pmic-wrap.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-scpsys-mt6991-mmpc.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-scpsys-mt6991-spm.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-scpsys.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-smi-dbg.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-smi.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-socinfo.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-spmi-pmic-adc.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-spmi-pmic.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-swpm-perf-arm-pmu.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-uart-apdma.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-vmm-notifier-mt6991.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_2p_charger.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_battery_manager.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_battery_oc_throttling.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_bp_thl.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_charger_algorithm_class.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_charger_framework.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_chg_type_det.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_cpu_power_throttling.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_dcm.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_disp_notify.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_dpc_v2.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_dramc.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_dynamic_loading_throttling.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_et.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_iommu_util.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_low_battery_throttling.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_mbraink_bridge.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_mdpm.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_panel_ext.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_pbm.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_pd_adapter.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_pd_charging.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_pep.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_pep20.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_pep40.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_pep45.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_printk_ctrl.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_rpmsg_mbox.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_slbc.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_sync.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_tinysys_ipi.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_ufcs_adapter.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_ut_test.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_vdisp_v2.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_wdt.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtu3.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mux_switch.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/nvmem-mt6681-efuse.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/nvmem_mtk-devinfo.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/nxp_i2c.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66.user/drivers/mtd/parsers/ofpart.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/p73.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/panel-p10u-36-02-0b-dsc-vdo.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/panel-p10u-42-02-0a-dsc-vdo.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/pcie-mediatek-gen3.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/pd-chk-mt6991.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/pd_dbg_info.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/pd_single_cp_manager.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/perf_helper.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/phy-mtk-mt6379-eusb2-repeater.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/phy-mtk-nxp-eusb2-repeater.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/phy-mtk-pcie.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/phy-mtk-ufs.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/phy-mtk-xsphy.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/pidmap.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/pinctrl-mt6363.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/pinctrl-mt6373.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/pinctrl-mt6991.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/pinctrl-mtk-common-v2_debug.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/pinctrl-mtk-v2.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/pkvm_mgmt.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/pkvm_mkp.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/pkvm_smmu.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/pkvm_tmem.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/pmic_lbat_service.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/pmic_lvsys_notify.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/ps5170.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/pwm-mtk-disp.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66.user/drivers/power/reset/reboot-mode.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/reset-ti-syscon.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66.user/net/rfkill/rfkill.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/rpmb-mtk.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/rpmb.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/rps_perf.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/rt4803.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/rt4831a_drv.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/rt_pd_manager.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/rtc-mt6685.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/sc8585_charger.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/sec-rng.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/sec.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/sgm38120.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/simtray.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/slbc_ipi.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/slbc_trace.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/slc-parity.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/smap-mt6991.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/smmu_secure.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/smpu-hook-v1.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/smpu.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/spi-mt65xx.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/spmi-mtk-mpu.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/spmi-mtk-pmif.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66.user/drivers/power/reset/syscon-reboot-mode.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/system_heap.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/systracker.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/tcpc_class.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/tcpc_mt6379.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/tcpci_late_sync.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/teeperf.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/timer-mediatek.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/tinysys-scmi.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/uarthub_drv.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/ufcs_class.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/ufcs_mt6379.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/ufs-mediatek-dbg.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/ufs-mediatek-mod-ise.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/uload_ind.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/usb_boost.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/usb_dp_selector.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/usb_meta.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66.user/drivers/media/v4l2-core/v4l2-flash-led-class.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/vcp_status_v2.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/vcp_v2.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/wl2868c.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/wlan_page_pool.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/xhci-mtk-hcd-v2.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66.user/drivers/block/zram/zram.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/zsmalloc.ko

BOARD_VENDOR_KERNEL_MODULES := \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/adsp-v2.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/apu_aov.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/apu_top.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/apusys.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/atf_logger.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/audio_ipi.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/backlight_cooling.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/binder_prio.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66.user/net/bluetooth/bluetooth.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/board_temp.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/bq25985_charger.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/btmtk_uart_unify.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/c2k_usb.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/c2k_usb_f_via_atc.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/c2k_usb_f_via_ets.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/c2k_usb_f_via_modem.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/c2ps_perf_ioctl.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/cam_fs.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/cam_log.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/camera_af_media.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/camera_dpe_isp8.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/camera_eeprom_v4l2.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/ccci_auxadc.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/ccci_ccif.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/ccci_dpmaif.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/ccci_fsm_scp.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/ccci_md_all.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/ccci_util_lib.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/ccd_rpmsg.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/ccmni.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66.user/net/wireless/cfg80211.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/charger_cooling.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/clk-dbg-mt6991.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/clk-disable-unused.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/cmdq-sec-drv.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/cmdq-test.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/connadp.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/connfem.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/conninfra.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/connscp.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/cpu_isolate_cooling.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/cpudvfs.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/cpufreq_sugov_ext.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/cpuqos_ext.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/cpuqos_v3.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/dio_dma_mapper.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/dw9781c.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/dw9781d.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/eas_ext.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/elliptic-ultrasound.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/emi-fake-eng.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/et7480.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/fhctl.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/flashlight.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/fpsgo.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/frs.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/fs3002_haptic.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/game.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/ged.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/gps_drv_dl_v062.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/gps_pwr.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/gps_scp.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/gz_ipc_mod.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/gz_irq_mod.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/gz_log_mod.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/gz_main_mod.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/gz_trusty_mod.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/gz_tz_system.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/gz_virtio_mod.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/hbt.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/hf_manager.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/imgsensor-glue_isp8.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/imgsensor_isp8.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/iommu_engine.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/iommu_test.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/isp_pspm_ioctl.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/jank_detection_common_utils.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/jank_detection_core.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/jpeg-driver.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/leds-mt6379.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/leds-mt6379pmic.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/load_track.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/lpm-gov-MHSP.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66.user/net/mac80211/mac80211.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/main2_vcm.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/main3_vcm.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/main4_vcm.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/main_vcm.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mali_kbase_mt6991_r49.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mali_mgm_mt6991_r49.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mali_prot_alloc_mt6991_r49.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mcupm.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/md_cooling_all.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mddp.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/met.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/met_backlight_api.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/met_emi_api.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/met_gpu_adv_api.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/met_gpu_api.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/met_gpueb_api.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/met_ipi_api.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/met_mcupm_api.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/met_scmi_api.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/met_sspm_api.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/met_vcore_api.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mi_gps_pwr.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mi_t1_gpio.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mi_thermal_interface.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mt6681-accdet.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mt6991-mt6681.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-cam-isp8.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-composite.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-dvfsrc-start.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-ipesys-me.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-lpm-dbg-common-v2.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-lpm-dbg-mt6991.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-lpm-plat-v2.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-lpm.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-mbox.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-mmdvfs-v3-start.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-pm-domain-disable-unused.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-pmic-oc-debug.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-pwm.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-scp-ultra.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-scp-vow.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-smmuv3-lmu.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-smmuv3-mpam-mon.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-smmuv3-pmu.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-soc-offload-common.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-sp-spk-amp.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-ssc-dbg-v2.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-ssc.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-swpm-audio-dbg-v6991.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-swpm-cpu-dbg-v6991.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-swpm-dbg-common-v1.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-swpm-dbg-v6991.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-swpm-disp-dbg-v6991.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-swpm-isp-dbg-v6991.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-swpm-isp-wrapper.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-swpm-mml-dbg-v6991.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-swpm.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-vcodec-common.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-vcodec-dec-v2.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-vcodec-enc-v2.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-vmm-isp71-regulator.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk-vow.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_aov.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_c2ps.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_ccd_remoteproc.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_ccuv.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_cg_peak_power_throttling.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_cm_ipi.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_cm_mgr.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_cm_mgr_mt6991.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_core_ctl.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_disp_sec.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_dynamic_loading_throttling.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_em.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_et.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_fpsgo.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_game.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_ghpm.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_gpu_hal.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_gpu_iommu_mt6991.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_gpu_pdma_mt6991.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_gpu_power_throttling.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_gpu_qos.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_gpueb.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_gpufreq_mt6991.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_gpufreq_wrapper.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_hcp_isp8.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_heap_debug.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_heap_refill.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_img_frm_sync.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_imgsys_cmdq_isp8.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_imgsys_isp8.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_imgsys_v4l2.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_ioctl_powerhal.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_ioctl_touch_boost.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_irtx_pwm.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_jpeg.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_mae.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_mae_isp8.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_mbraink.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_mbraink_bridge.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_mbraink_v6991.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_md_power_throttling.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_mdpm.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_pbm.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_pcie_smt.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_peak_power_budget.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_pelt_hint.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_perf_common.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_perf_ioctl.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_perf_ioctl_magt.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_qos.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_rpmsg_mbox.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_sec_heap.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_smmu_qos.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_tinysys_ipi.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_u_ether.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/mtk_usb_f_rndis.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/nt38771_touch_dash.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/nvmem-mt635x-efuse.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/pda_drv_mt6991.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/pmic_temp.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/pmsr_v3.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/powerhal_cpu_ctrl.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/powersave.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66.user/drivers/power/reset/reboot-mode.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/richtek_spm_cls.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/rps_perf.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/sapu.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/sc858x_charger.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/scheduler.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/scheduler_ext.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/scp.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/sec.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/sensorhub.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/sgm38120.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/sgm38121.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/si_haptic.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/slbc_mt6991.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/snd-soc-audiodsp-common.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/snd-soc-aw882xx.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/snd-soc-fs19xx.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/snd-soc-mt6681.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/snd-soc-mt6991-afe.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/snd-soc-mtk-common.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/snd-soc-mtk-scp-ultra.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/snd-soc-rt5512.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/soc_temp_lvts.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/spmi-mtk-mpu.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/sspm_v3.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/stmvl53l4.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/sub_vcm.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66.user/drivers/power/reset/syscon-reboot-mode.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/task_turbo.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/task_turbo_v.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66.user/drivers/thermal/thermal-generic-adc.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/thermal_interface.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/thermal_trace.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/tmem_ffa.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/touch_boost.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/trace_mmstat.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/tui-common.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/uarthub_drv.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/uload_ind.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/unionpower.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/usb_offload.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/vdec-fmt.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/vtskin_temp.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/widevine_driver.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/wifi_cooling.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/wl2866d.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/wl2868c.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/wla-v1-dbg.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/wla-v1.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/wlan_drv_gen4m_6991_6639_new9gen2.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/wlan_drv_gen4m_6991_6653.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/wmt_chrdev_wifi_connac3.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/xiaomi_spi_tee.ko \
    $(DASH_KLEAF_OUT)/mgk_64_k66_customer_modules_install.user/xiaomi_touch_dash.ko

BOARD_VENDOR_RAMDISK_KERNEL_MODULES_LOAD := $(strip $(file <$(DEVICE_PATH)/kernel/modules.load.platform))
BOARD_VENDOR_KERNEL_MODULES_LOAD := $(strip $(file <$(DEVICE_PATH)/kernel/modules.load.vendor_dlkm))
